### ISSUE TITLE
Count assignments graded as 0 without submissions as incomplete 

### ISSUE THREAD

**Issue by Powerlated** [jtcheng26/canvas-task-extension#59]
Currently, zeros put in for unsubmitted assignments are shown as complete in dashboard task rings. Displaying those assignments as incomplete would be helpful for when a professor or teacher has flexible deadlines but enters unsubmitted work as zeros to remind students to complete their work.

**Comment by jtcheng26** [comment]
Yes, this is the intended behavior. I'll look into it and see what's going wrong.

**Comment by jtcheng26** [comment]
Update: as of v1.2.0, the extension began using a different api route that does not include the actual grade, so this functionality would require a separate api request, which might slow down the initial load time. Will look for a better solution, since this is a really helpful feature. For now, manually marking those assignments as unfinished is a workaround.

**Comment by jtcheng26** [comment]
Update: 
merging data from this route: 

/api/v1/users/self/graded_submissions

would solve this issue, but only for recently graded assignments and may increase load time. I'll try it out and see if it's a good solution.
