### ISSUE TITLE
Align to right edge of viewport on 1920x1080 display

### ISSUE THREAD

**Issue by memtech3** [jtcheng26/canvas-task-extension#60]
Super cool extension! Could you fix the allignment of the overlay so that it is aligned with the right edge of the viewport on a 1920x1080 display?

![image](https://user-images.githubusercontent.com/20732350/208612352-b33ced8a-0653-45fc-91ff-aa1a1e61cc59.png)

**Comment by jtcheng26** [comment]
Thanks for bringing this up, someone else also emailed about this issue earlier! This happens because Canvas has this CSS rule
```
body:not(.full-width):not(.outcomes):not(.body--login-confirmation) .ic-Layout-wrapper {
    max-width: 1366px;
}
```
and some schools (including yours) don't apply the `.full-width` class. Fixed by having the extension add it to the body element. I'll include it in the next update which should be in 1 or 2 weeks.

**Comment by memtech3** [comment]
Thanks!
